import {
  Warehouse,
  Search,
  PenTool,
  CircleDot,
  Package,
  ShieldCheck,
  Layers,
  Sparkles,
  Wrench,
  Bot,
  FlaskConical,
  Magnet,
  Boxes,
  Flame,
  Thermometer,
  Zap,
  Settings2,
  Cog,
  Truck,
  type LucideIcon,
} from "lucide-react";
import { FactoryZone } from "@/types";

// 구역 카테고리별 아이콘 (걸어다니며 훑어볼 때 이름을 다 읽지 않아도 구역 성격을 구분할 수 있도록)
export const ZONE_CATEGORY_ICON: Partial<Record<FactoryZone["category"], LucideIcon>> = {
  warehouse: Warehouse,
  inspection: Search,
  marking: PenTool,
  grinding: CircleDot,
  packaging: Package,
  quality: ShieldCheck,
  end_process: Layers,
  sheet_grinding: Layers,
  pt_buffing: Sparkles,
  correction: Wrench,
  auto_robot: Bot,
  sample_reagent: FlaskConical,
  mt: Magnet,
  material: Boxes,
  forging: Flame,
  heat_treatment: Thermometer,
  welding: Zap,
  lathe: Settings2,
  machining: Cog,
  logistics: Truck,
};
